[workspace]
members = [ "crates/*", "website/website-gen" ]

[profile.release]
incremental = true
debug = 1 # only line info

[patch.'crates-io']
instant = { git = "https://github.com/JasperDeSutter/instant.git" }
