[package]
name = "ra_shims"
version = "0.1.0"
authors = ["JasperDeSutter <jasper.desutter@gmail.com>"]
edition = "2018"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web_sys = { package = "web-sys", version = "0.3", features = ['Window', 'Performance', 'PerformanceTiming'] }
